pages = [{"l":"api/index.html","n":"API","t":" API","d":"api"},
{"l":"api/little/security.html","n":"little.security","t":"package little.security","d":"little/security"},
{"l":"api/little/security/GroupPermission$.html","n":"GroupPermission","t":"object GroupPermission","d":"little/security/GroupPermission$"},
{"l":"api/little/security/GroupPermission$.html","n":"apply","t":"def apply(groupId: String): Permission","d":"little/security/GroupPermission$"},
{"l":"api/little/security/GroupPermission$.html","n":"toSet","t":"def toSet(ids: Iterable[String]): Set[Permission]","d":"little/security/GroupPermission$"},
{"l":"api/little/security/GroupPermission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"little/security/GroupPermission$"},
{"l":"api/little/security/GroupPermission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"little/security/GroupPermission$"},
{"l":"api/little/security/Permission.html","n":"Permission","t":"trait Permission","d":"little/security/Permission"},
{"l":"api/little/security/Permission.html","n":"name","t":"def name: String","d":"little/security/Permission"},
{"l":"api/little/security/Permission$.html","n":"Permission","t":"object Permission","d":"little/security/Permission$"},
{"l":"api/little/security/Permission$.html","n":"apply","t":"def apply(name: String): Permission","d":"little/security/Permission$"},
{"l":"api/little/security/Permission$.html","n":"toSet","t":"def toSet(names: Iterable[String]): Set[Permission]","d":"little/security/Permission$"},
{"l":"api/little/security/Permission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"little/security/Permission$"},
{"l":"api/little/security/Permission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"little/security/Permission$"},
{"l":"api/little/security/RootContext$.html","n":"RootContext","t":"object RootContext extends SecurityContext","d":"little/security/RootContext$"},
{"l":"api/little/security/RootContext$.html","n":"test","t":"def test(perm: Permission): Boolean","d":"little/security/RootContext$"},
{"l":"api/little/security/RootContext$.html","n":"toString","t":"val toString: String","d":"little/security/RootContext$"},
{"l":"api/little/security/SecurityContext.html","n":"SecurityContext","t":"trait SecurityContext","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"test","t":"def test(perm: Permission): Boolean","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"apply","t":"def apply[T](perm: Permission)(op: => T): T","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"any","t":"def any[T](perms: Set[Permission])(op: => T): T","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"any","t":"def any[T](one: Permission, more: Permission*)(op: => T): T","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"all","t":"def all[T](perms: Set[Permission])(op: => T): T","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityContext.html","n":"all","t":"def all[T](one: Permission, more: Permission*)(op: => T): T","d":"little/security/SecurityContext"},
{"l":"api/little/security/SecurityViolation.html","n":"SecurityViolation","t":"class SecurityViolation(message: String) extends RuntimeException","d":"little/security/SecurityViolation"},
{"l":"api/little/security/UserContext.html","n":"UserContext","t":"trait UserContext extends SecurityContext","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"userId","t":"def userId: String","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"groupId","t":"def groupId: String","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"permissions","t":"def permissions: Set[Permission]","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"grant","t":"def grant(perms: Set[Permission]): UserContext","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"grant","t":"def grant(one: Permission, more: Permission*): UserContext","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"revoke","t":"def revoke(perms: Set[Permission]): UserContext","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext.html","n":"revoke","t":"def revoke(one: Permission, more: Permission*): UserContext","d":"little/security/UserContext"},
{"l":"api/little/security/UserContext$.html","n":"UserContext","t":"object UserContext","d":"little/security/UserContext$"},
{"l":"api/little/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String): UserContext","d":"little/security/UserContext$"},
{"l":"api/little/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String, permissions: Set[Permission]): UserContext","d":"little/security/UserContext$"},
{"l":"api/little/security/UserContext$.html","n":"apply","t":"def apply(userId: String, groupId: String, one: Permission, more: Permission*): UserContext","d":"little/security/UserContext$"},
{"l":"api/little/security/UserContext$.html","n":"unapply","t":"def unapply(security: UserContext): Option[(String, String, Set[Permission])]","d":"little/security/UserContext$"},
{"l":"api/little/security/UserPermission$.html","n":"UserPermission","t":"object UserPermission","d":"little/security/UserPermission$"},
{"l":"api/little/security/UserPermission$.html","n":"apply","t":"def apply(userId: String): Permission","d":"little/security/UserPermission$"},
{"l":"api/little/security/UserPermission$.html","n":"toSet","t":"def toSet(ids: Iterable[String]): Set[Permission]","d":"little/security/UserPermission$"},
{"l":"api/little/security/UserPermission$.html","n":"toSet","t":"def toSet(one: String, more: String*): Set[Permission]","d":"little/security/UserPermission$"},
{"l":"api/little/security/UserPermission$.html","n":"unapply","t":"def unapply(perm: Permission): Option[String]","d":"little/security/UserPermission$"},
{"l":"api/index.html","n":"API","t":" API","d":"api"}];